/**
 * TinaCMS Client Utility
 *
 * The full typed client is auto-generated by TinaCMS after running:
 *   npm run tina:dev
 *
 * The generated client lives at: tina/__generated__/client.ts
 * That file is gitignored and only exists after the first `tina:dev` run.
 *
 * Usage (once generated):
 *   import { client } from '../../../tina/__generated__/client'
 *   const result = await client.queries.page({ relativePath: 'home.md' })
 *
 * The constants below document the local dev GraphQL endpoint for reference.
 */

export const TINA_GRAPHQL_URL = 'http://localhost:4001/graphql'

export const TINA_CONFIG = {
  url: TINA_GRAPHQL_URL,
  token: '',
} as const
